export const platforms = [
  {
    id: 'douyin',
    name: '抖音',
    title: '热榜',
    icon: '/logos/douyin.png',
    api: 'https://api.ikangjia.cn/douyin',
  },
  {
    id: 'bilibili',
    name: '哔哩哔哩',
    title: '热门',
    icon: '/logos/bilibili.png',
    api: 'https://api.ikangjia.cn/bilibili',
  },
  {
    id: 'weibo',
    name: '微博',
    title: '热搜',
    icon: '/logos/weibo.png',
    api: 'https://api.ikangjia.cn/weibo',
  },
  {
    id: 'zhihu',
    name: '知乎',
    title: '热榜',
    icon: '/logos/zhihu.png',
    api: 'https://api.ikangjia.cn/zhihu',
  },
  {
    id: '36kr',
    name: '36氪',
    title: '热榜',
    icon: '/logos/36kr.png',
    api: 'https://api.ikangjia.cn/36kr',
  },
  {
    id: 'qq-news',
    name: '腾讯新闻',
    title: '热点',
    icon: '/logos/qq-news.png',
    api: 'https://api.ikangjia.cn/qq-news',
  },
  {
    id: 'netease-news',
    name: '网易新闻',
    title: '热榜',
    icon: '/logos/netease-news.png',
    api: 'https://api.ikangjia.cn/netease-news',
  },
  {
    id: 'thepaper',
    name: '澎湃新闻',
    title: '热榜',
    icon: '/logos/thepaper.png',
    api: 'https://api.ikangjia.cn/thepaper',
  },
  {
    id: 'toutiao',
    name: '今日头条',
    title: '热榜',
    icon: '/logos/toutiao.png',
    api: 'https://api.ikangjia.cn/toutiao',
  },
  {
    id: 'huxiu',
    name: '虎嗅网',
    title: '热榜',
    icon: '/logos/huxiu.png',
    api: 'https://api.ikangjia.cn/huxiu',
  },
  {
    id: 'baidu',
    name: '百度',
    title: '热搜',
    icon: '/logos/baidu.png',
    api: 'https://api.ikangjia.cn/baidu',
  },
  {
    id: 'sina-news',
    name: '新浪新闻',
    title: '热点榜',
    icon: '/logos/weibo.png',
    api: 'https://api.ikangjia.cn/sina-news',
  },
  {
    id: 'sina',
    name: '新浪网',
    title: '热榜',
    icon: '/logos/weibo.png',
    api: 'https://api.ikangjia.cn/sina',
  },
  {
    id: 'sspai',
    name: '少数派',
    title: '热榜',
    icon: '/logos/sspai.png',
    api: 'https://api.ikangjia.cn/sspai',
  },
  {
    id: 'ithome',
    name: 'IT 之家',
    title: '热榜',
    icon: '/logos/ithome.png',
    api: 'https://api.ikangjia.cn/ithome',
  },

  {
    id: 'HelloGitHub',
    name: 'HelloGitHub',
    title: 'Trending',
    icon: '/logos/github.png',
    api: 'https://api.ikangjia.cn/hellogithub',
  },
  {
    id: '51cto',
    name: '51CTO',
    title: '排行榜',
    icon: '/logos/woshipm.png',
    api: 'https://api.ikangjia.cn/51cto',
  },

  {
    id: 'juejin',
    name: '稀土掘金',
    title: '热榜',
    icon: '/logos/juejin.png',
    api: 'https://api.ikangjia.cn/juejin',
  },
  {
    id: 'csdn',
    name: 'CSDN',
    title: '排行榜',
    icon: '/logos/csdn.png',
    api: 'https://api.ikangjia.cn/csdn',
  },
  {
    id: 'v2ex',
    name: 'V2EX',
    title: '最热',
    icon: '/logos/v2ex.png',
    api: 'https://api.ikangjia.cn/v2ex',
  },
  {
    id: 'zhihu-daily',
    name: '知乎日报',
    title: '日报',
    icon: '/logos/zhihu-daily.png',
    api: 'https://api.ikangjia.cn/zhihu-daily',
  },
  {
    id: 'hupu',
    name: '虎扑',
    title: '步行街热榜',
    icon: '/logos/hupu.png',
    api: 'https://api.ikangjia.cn/hupu',
  },
  {
    id: 'tieba',
    name: '百度贴吧',
    title: '热议',
    icon: '/logos/tieba.png',
    api: 'https://api.ikangjia.cn/tieba',
  },
  {
    id: 'douban-movie',
    name: '豆瓣电影',
    title: '新片榜',
    icon: '/logos/douban-movie.png',
    api: 'https://api.ikangjia.cn/douban-movie',
  },
  {
    id: 'douban-group',
    name: '豆瓣小组',
    title: '豆瓣讨论',
    icon: '/logos/douban-group.png',
    api: 'https://api.ikangjia.cn/douban-group',
  },
  {
    id: 'weread',
    name: '微信读书',
    title: '读书榜单',
    icon: '/logos/weread.png',
    api: 'https://api.ikangjia.cn/weread',
  },
  {
    id: 'history',
    name: '历史上的今天',
    title: '月-日',
    icon: '/logos/history.png',
    api: 'https://api.ikangjia.cn/history',
  },

  {
    id: 'ifanr',
    name: '爱范儿',
    title: '快讯',
    icon: '/logos/woshipm.png',
    api: 'https://api.ikangjia.cn/ifanr',
  },
  {
    id: 'ithome-xijiayi',
    name: 'IT之家「喜加一」',
    title: '最新动态',
    icon: '/logos/ithome.png',
    api: 'https://api.ikangjia.cn/ithome-xijiayi',
  },
  {
    id: 'jianshu',
    name: '简书',
    title: '热门推荐',
    icon: '/logos/jianshu.png',
    api: 'https://api.ikangjia.cn/jianshu',
  },
  {
    id: 'acfun',
    name: 'ACFun',
    title: '排行榜',
    icon: '/logos/acfun.png',
    api: 'https://api.ikangjia.cn/acfun',
  },
  {
    id: 'nga',
    name: 'NGA',
    title: '热帖',
    icon: '/logos/ngabbs.png',
    api: 'https://api.ikangjia.cn/ngabbs',
  },
  {
    id: 'weatheralarm',
    name: '中央气象台',
    title: '全国气象预警',
    icon: '/logos/woshipm.png',
    api: 'https://api.ikangjia.cn/weatheralarm',
  },
  {
    id: 'nodeseek',
    name: 'NodeSeek',
    title: '最新动态',
    icon: '/logos/woshipm.png',
    api: 'https://api.ikangjia.cn/nodeseek',
  },
  // 游戏
  {
    id: 'lol',
    name: '英雄联盟',
    title: '更新公告',
    icon: '/logos/lol.png',
    api: 'https://api.ikangjia.cn/lol',
  },
  {
    id: 'starrail',
    name: '崩坏：星穹铁道',
    title: '最新动态',
    icon: '/logos/starrail.png',
    api: 'https://api.ikangjia.cn/starrail',
  },
  {
    id: 'genshin',
    name: '原神',
    title: '最新消息',
    icon: '/logos/honkai.png',
    api: 'https://api.ikangjia.cn/genshin',
  },
  {
    id: 'honkai',
    name: '崩坏3',
    title: '最新动态',
    icon: '/logos/starrail.png',
    api: 'https://api.ikangjia.cn/honkai',
  },
  // {
  //   id: 'earthquake',
  //   name: '中国地震台',
  //   title: '地震速报',
  //   icon: '/logos/woshipm.png',
  //   api: 'https://api.ikangjia.cn/earthquake',
  // },
  // {
  //   id: '52pojie',
  //   name: '吾爱破解',
  //   title: '榜单',
  //   icon: '/logos/woshipm.png',
  //   api: 'https://api.ikangjia.cn/52pojie',
  // },
  // {
  //   id: 'guokr',
  //   name: '果壳',
  //   title: '热门文章',
  //   icon: '/logos/woshipm.png',
  //   api: 'https://api.ikangjia.cn/guokr',
  // },
  // {
  //   id: 'coolapk',
  //   name: '酷安',
  //   title: '热榜',
  //   icon: '/logos/woshipm.png',
  //   api: 'https://api.ikangjia.cn/coolapk',
  // },
  // {
  //   id: 'woshipm',
  //   name: '人人都是产品经理',
  //   title: '热榜',
  //   icon: '/logos/woshiipm.png',
  //   api: 'https://api.ikangjia.cn/woshipm',
  // },
];
